# categorical data preprocessing 
### label
### One hot 
### Ordinal 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

# Label Encoder

In [2]:
color =['Red','Black','Blue','Green','Orange']
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
encode=le.fit_transform(color)
print(encode)

[4 0 1 2 3]


In [2]:
df=pd.read_csv("social_media.csv")
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,5.480462,1.412655,9,False,False,4,5,21.776927,NaN
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,3.045393,0.148936,3,False,False,1,29,4.111370,6.155613
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,5.491520,1.224296,10,False,False,1,2,1.888315,6.285237
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,6.816069,0.234483,1,False,False,2,9,12.511871,7.854711


In [4]:
df.gender.unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [6]:
df['gender_enc']=le.fit_transform(df['gender'])


In [7]:
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,gender_enc
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688,1
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427,1
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944,1
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670,0
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,5.480462,1.412655,9,False,False,4,5,21.776927,NaN,0
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,3.045393,0.148936,3,False,False,1,29,4.111370,6.155613,1
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,5.491520,1.224296,10,False,False,1,2,1.888315,6.285237,1
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,6.816069,0.234483,1,False,False,2,9,12.511871,7.854711,0


# one hot encoder

In [8]:
df=pd.DataFrame({"animals":['cat','dog','fox']})
print(df)

  animals
0     cat
1     dog
2     fox


In [10]:
encoded_df=pd.get_dummies(df,columns=['animals'],dtype=int)
print(encoded_df)

   animals_cat  animals_dog  animals_fox
0            1            0            0
1            0            1            0
2            0            0            1


In [11]:
#sklearn
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
dff=ohe.fit_transform(df)
print(dff)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
df.job_type.unique()

array(['Unemployed', 'Health', 'Finance', 'IT', 'Education', 'Student'],
      dtype=object)

In [17]:
en=pd.get_dummies(df['job_type'],prefix='job_type', dtype=int)
print(en)

       job_type_Education  job_type_Finance  job_type_Health  job_type_IT  \
0                       0                 0                0            0   
1                       0                 0                1            0   
2                       0                 1                0            0   
3                       0                 0                0            0   
4                       0                 0                0            1   
...                   ...               ...              ...          ...   
29995                   0                 0                1            0   
29996                   0                 0                1            0   
29997                   1                 0                0            0   
29998                   1                 0                0            0   
29999                   0                 0                0            0   

       job_type_Student  job_type_Unemployed  
0                     0     

In [20]:
df=pd.concat([df,en],axis=1)
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,...,job_type_Health,job_type_IT,job_type_Student,job_type_Unemployed,job_type_Education,job_type_Finance,job_type_Health,job_type_IT,job_type_Student,job_type_Unemployed
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,...,0,0,0,1,0,0,0,0,0,1
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,...,1,0,0,0,0,0,1,0,0,0
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,...,0,0,0,0,0,1,0,0,0,0
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,...,0,0,0,1,0,0,0,0,0,1
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,...,1,0,0,0,0,0,1,0,0,0
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,...,1,0,0,0,0,0,1,0,0,0
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,...,0,0,0,0,1,0,0,0,0,0
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,...,0,0,0,0,1,0,0,0,0,0


In [22]:

encode=ohe.fit_transform(df[['job_type']])
encode

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
en_dff=pd.DataFrame(encode)

In [25]:
df=pd.concat([df,en_dff],axis=1)
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,...,2,3,4,5,0,1,2,3,4,5
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0


In [28]:
from sklearn.preprocessing import OrdinalEncoder
education=[['ssc'],['pg'],['ug'],['inter']]
oe=OrdinalEncoder(categories=[['ssc','inter','ug','pg']])
ev=oe.fit_transform(education)
ev

array([[0.],
       [3.],
       [2.],
       [1.]])

In [30]:
df.social_platform_preference.unique()

array(['Facebook', 'Twitter', 'Telegram', 'TikTok', 'Instagram'],
      dtype=object)

In [45]:
e=OrdinalEncoder(categories=[['Instagram','TikTok','Telegram','Twitter','Facebook']])
v=e.fit_transform(df[['social_platform_preference']])
v

array([[4.],
       [3.],
       [3.],
       ...,
       [1.],
       [0.],
       [3.]])

In [46]:
enf=pd.DataFrame(v)

In [47]:
df=pd.concat([df,enf],axis=1)
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,...,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,0,0
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,...,0.419102,8,False,False,4,11,21.927072,6.336688,4.0,4.0
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,...,0.671519,7,True,True,2,25,0.000000,3.412427,3.0,3.0
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,...,0.624378,0,True,False,3,17,10.322044,2.474944,3.0,3.0
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,...,1.204540,1,False,False,0,4,23.876616,1.733670,4.0,4.0
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,...,1.876254,1,False,True,1,30,10.653519,9.693060,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,...,1.412655,9,False,False,4,5,21.776927,NaN,4.0,4.0
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,...,0.148936,3,False,False,1,29,4.111370,6.155613,0.0,0.0
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,...,1.224296,10,False,False,1,2,1.888315,6.285237,1.0,1.0
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,...,0.234483,1,False,False,2,9,12.511871,7.854711,0.0,0.0


# Column Transformer

In [2]:
num_clos=df.select_dtypes(include="number").columns
cat_clos=df.select_dtypes(include="object").columns


NameError: name 'df' is not defined

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder , StandardScaler

In [5]:
pre =ColumnTransformer(transformers=[("ohe",OneHotEncoder(),cat_clos),("sc",StandardScaler(),num_clos)])


In [6]:
prep=pre.fit_transform(df)
prep

array([[ 0.        ,  1.        ,  0.        , ..., -0.49250667,
         1.58872949,  0.64671729],
       [ 0.        ,  1.        ,  0.        , ...,  1.02054852,
        -1.42310937, -0.73190023],
       [ 0.        ,  1.        ,  0.        , ...,  0.15594556,
        -0.00530341, -1.17386876],
       ...,
       [ 0.        ,  1.        ,  0.        , ..., -1.46518501,
        -1.16373598,  0.62246125],
       [ 1.        ,  0.        ,  0.        , ..., -0.70865741,
         0.29548475,  1.36237611],
       [ 0.        ,  1.        ,  0.        , ..., -1.24903427,
        -0.55433216,  1.14272147]])

In [7]:
dfff=pd.DataFrame(prep)
dfff

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.250337,1.242338,-0.528229,-0.945166,-0.928250,0.947731,1.418913,-0.492507,1.588729,0.646717
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,-0.220971,0.113250,0.518419,-0.953806,-0.541903,0.632640,0.000496,1.020549,-1.423109,-0.731900
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.814815,-0.784643,-0.528229,1.422819,-0.614058,-1.572998,0.709705,0.155946,-0.005303,-1.173869
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.282056,-1.686859,0.169536,-0.305512,0.273933,-1.257907,-1.417920,-1.249034,1.856513,-1.523336
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.659685,NaN,0.518419,-0.747649,1.302050,-1.257907,-0.708712,1.560925,0.040227,2.229050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,-1.068468,-0.789017,0.867302,-0.696586,0.592471,1.262822,1.418913,-1.140959,1.568106,NaN
29996,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.296174,0.906626,0.867302,-2.359910,-1.341763,-0.627725,-0.708712,1.452850,-0.858384,0.561351
29997,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.532304,1.968364,-0.179346,-0.689032,0.304171,1.577914,-0.708712,-1.465185,-1.163736,0.622461
29998,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.115226,1.032089,0.867302,0.215728,-1.210827,-1.257907,0.000496,-0.708657,0.295485,1.362376
