In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.datasets import load_iris
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score ,classification_report 
import math

In [2]:
df=pd.read_csv("banana_quality_dataset.csv")

In [3]:
df.drop(["sample_id","harvest_date"],axis=1,inplace=True)   

In [4]:
x =df.drop(['quality_category'],axis=1)

In [5]:
y=df['quality_category']

In [15]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   variety             1000 non-null   object 
 1   region              1000 non-null   object 
 2   quality_score       1000 non-null   float64
 3   ripeness_index      1000 non-null   float64
 4   ripeness_category   1000 non-null   object 
 5   sugar_content_brix  1000 non-null   float64
 6   firmness_kgf        1000 non-null   float64
 7   length_cm           1000 non-null   float64
 8   weight_g            1000 non-null   float64
 9   tree_age_years      1000 non-null   float64
 10  altitude_m          1000 non-null   float64
 11  rainfall_mm         1000 non-null   float64
 12  soil_nitrogen_ppm   1000 non-null   float64
dtypes: float64(10), object(3)
memory usage: 101.7+ KB


In [17]:
num_cols = x.select_dtypes(include=['int64', 'float64']).columns
cat_cols = x.select_dtypes(include=['object']).columns
num_cols

Index(['quality_score', 'ripeness_index', 'sugar_content_brix', 'firmness_kgf',
       'length_cm', 'weight_g', 'tree_age_years', 'altitude_m', 'rainfall_mm',
       'soil_nitrogen_ppm'],
      dtype='object')

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

ct = ColumnTransformer(transformers=[
    ("oe", OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cat_cols),
    ("sc", StandardScaler(), num_cols)
], remainder='passthrough')

In [21]:
x_transformed=ct.fit_transform(x)

In [22]:
x_transformed=pd.DataFrame(x_transformed,columns=x.columns)
x_transformed

,variety,region,quality_score,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,5.0,1.0,3.0,-1.082350,-1.102626,-0.829400,0.638798,0.271721,-0.362627,0.541038,-1.557632,0.828641,1.478299
1,6.0,4.0,2.0,-0.083531,0.118602,-0.878570,1.073376,1.086240,-0.086672,-1.108701,-1.037919,0.711835,0.100944
2,1.0,3.0,1.0,2.043584,1.254230,1.388129,-0.835662,0.927522,1.231846,1.308358,1.225172,-1.385170,0.808285
3,5.0,3.0,2.0,-0.471961,0.769163,-0.868736,0.468071,-1.186389,-0.548225,0.406757,0.998792,1.545781,-0.216332
4,7.0,3.0,2.0,-0.213007,1.025963,-0.794982,0.281824,-1.203830,1.284148,-1.166250,-0.462490,0.290520,0.472345
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.0,3.0,2.0,1.914108,0.512362,1.250456,-0.168275,1.407163,0.643306,0.291659,-0.734754,0.100866,1.280467
996,2.0,7.0,1.0,-0.157518,1.539564,-1.188335,-0.548530,-1.306735,0.016506,0.598587,-0.958090,-1.138442,1.420442
997,6.0,3.0,0.0,-1.452283,-1.502094,-0.662225,-0.331241,-0.579424,0.922720,1.442639,-0.094945,1.741284,1.595878
998,3.0,4.0,0.0,-0.823397,-1.542040,-0.731062,0.134378,1.121123,-0.045564,-0.514028,1.496265,-1.342099,-0.352575


In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_transformed,y,test_size=0.2)

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# create model
lr = LogisticRegression()

# train model
lr.fit(x_train, y_train)

# prediction
y_pred = lr.predict(x_test)

# evaluation
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred,average="micro"))
print("Recall   :", recall_score(y_test, y_pred,average="micro"))
print("F1 Score :", f1_score(y_test, y_pred,average="micro"))

# confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy : 0.955
Precision: 0.955
Recall   : 0.955
F1 Score : 0.955

Confusion Matrix:
[[92  0  2  0]
 [ 4  1  0  0]
 [ 3  0 92  0]
 [ 0  0  0  6]]


In [34]:
y_train_pred = lr.predict(x_train)

# testing prediction
y_test_pred = lr.predict(x_test)

# accuracies
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

print("Training Accuracy :", train_acc)
print("Testing Accuracy  :", test_acc)

Training Accuracy : 0.9675
Testing Accuracy  : 0.955
