In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
corpus=["I love NLP","I love machine learning ","NLP is usefull in data science",
        "Machine learning is part of data science",
        "I enjoy learning NLP"]


In [14]:
vect=CountVectorizer(binary=True)

In [15]:
bag=vect.fit_transform(corpus)

In [16]:
print("Vocabulary:",vect.get_feature_names_out())
print("Bow Matrix:\n", bag.toarray())

Vocabulary: ['data' 'enjoy' 'in' 'is' 'learning' 'love' 'machine' 'nlp' 'of' 'part'
 'science' 'usefull']
Bow Matrix:
 [[0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0]
 [1 0 1 1 0 0 0 1 0 0 1 1]
 [1 0 0 1 1 0 1 0 1 1 1 0]
 [0 1 0 0 1 0 0 1 0 0 0 0]]


In [17]:
# if we put (binary=False) then it is    COUNT BASED BAG OF WORDS

In [18]:
import pandas as pd

In [19]:
df=pd.read_csv("amazon_reviews.csv")
df.head()

,sentiments,cleaned_review,review_score
0,positive,i wish would have gotten one earlier love it a...,5
1,neutral,i ve learned this lesson again open the packag...,1
2,neutral,it is so slow and lags find better option,2
3,neutral,roller ball stopped working within months of m...,1
4,neutral,i like the color and size but it few days out ...,1


In [20]:
df.isnull().sum()

sentiments        0
cleaned_review    3
review_score      0
dtype: int64

In [21]:
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17337 entries, 0 to 17339
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   sentiments      17337 non-null  object
 1   cleaned_review  17337 non-null  object
 2   review_score    17337 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 541.8+ KB


In [23]:
df.duplicated().sum()

np.int64(1347)

In [24]:
df=df.drop_duplicates()

In [25]:
bag=vect.fit_transform(df['cleaned_review'])
print("Vocabulary:",vect.get_feature_names_out())
print("Bow Matrix:\n",bag.toarray())

Vocabulary: ['aa' 'aaa' 'aaaaa' ... 'zooming' 'zooms' 'zumba']
Bow Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [31]:
from collections import Counter
import re

#Function to clean text and extract words
def get_words(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r"[^a-zA-Z\s]", "", text)  # Remove special characters
    words = text.split()
    return words
#Get all words from the dataset
all_words = df["cleaned_review"].apply(get_words).sum()
#Count word frequencies
word_counts = Counter(all_words)
#Display the most common words
print(word_counts.most_common(10))
!pip install wordcloud


[('the', 25196), ('it', 21988), ('and', 16675), ('to', 12547), ('for', 9503), ('is', 9264), ('this', 8208), ('my', 6368), ('mouse', 5828), ('of', 5307)]


In [32]:
from wordcloud import WordCloud

wordcloud = WordCloud(width=800, height=400, background_color="white").generate(" ".join(all_words))

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud of Reviews")
plt.show()

ModuleNotFoundError: No module named 'wordcloud'